version: '3.8'
name: awsgoo
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy # https://github.com/nginx-proxy/nginx-proxy
    ports:
      - "9889:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - blog-a
      - blog-b
    deploy:
      resources:
        limits:
          cpus: '0.02'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
          
  blog-a:
    build: blog-a/
    deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.02'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 10M
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com, romeo.com
      - VIRTUAL_PORT=80

  blog-b:
    build: blog-b/
    deploy:
      mode: replicated
      replicas: 1 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources: # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.02'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 10M
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=aws.google.com, juliet.com
      - VIRTUAL_PORT=80

